#!/usr/bin/env python3
# -*- coding: utf-8 -*-

num_isr = 256
pushes_error = [8, 10, 11, 12, 13, 14, 17]

print('''
.intel_syntax noprefix
.extern isr_common
''')


print('''
/*
Interrupt Service Routines
This file is autogenerated by the isr.py script, do not edit by hand

Each generated routine pushes a dummy argument if the CPU does not provide one,
followed by the ISR number.
*/
''')

for i in range(num_isr):
    print('''isr{0}:
    cli
    {1}
    push {0}
    jmp isr_common'''.format(i,
        'push 0' if i not in pushes_error else 'nop'))

print('')
print('''
// Vector table

.section .data
.global ISR_TABLE
ISR_TABLE:''')

for i in range(num_isr):
    print('  .quad isr{}'.format(i))