
.intel_syntax noprefix
.extern isr_common


/*
Interrupt Service Routines
This file is autogenerated by the isr.py script, do not edit by hand

Each generated routine pushes a dummy argument if the CPU does not provide one,
followed by the ISR number.
*/

isr0:
    cli
    push 0
    push 0
    jmp isr_common
isr1:
    cli
    push 0
    push 1
    jmp isr_common
isr2:
    cli
    push 0
    push 2
    jmp isr_common
isr3:
    cli
    push 0
    push 3
    jmp isr_common
isr4:
    cli
    push 0
    push 4
    jmp isr_common
isr5:
    cli
    push 0
    push 5
    jmp isr_common
isr6:
    cli
    push 0
    push 6
    jmp isr_common
isr7:
    cli
    push 0
    push 7
    jmp isr_common
isr8:
    cli
    nop
    push 8
    jmp isr_common
isr9:
    cli
    push 0
    push 9
    jmp isr_common
isr10:
    cli
    nop
    push 10
    jmp isr_common
isr11:
    cli
    nop
    push 11
    jmp isr_common
isr12:
    cli
    nop
    push 12
    jmp isr_common
isr13:
    cli
    nop
    push 13
    jmp isr_common
isr14:
    cli
    nop
    push 14
    jmp isr_common
isr15:
    cli
    push 0
    push 15
    jmp isr_common
isr16:
    cli
    push 0
    push 16
    jmp isr_common
isr17:
    cli
    nop
    push 17
    jmp isr_common
isr18:
    cli
    push 0
    push 18
    jmp isr_common
isr19:
    cli
    push 0
    push 19
    jmp isr_common
isr20:
    cli
    push 0
    push 20
    jmp isr_common
isr21:
    cli
    push 0
    push 21
    jmp isr_common
isr22:
    cli
    push 0
    push 22
    jmp isr_common
isr23:
    cli
    push 0
    push 23
    jmp isr_common
isr24:
    cli
    push 0
    push 24
    jmp isr_common
isr25:
    cli
    push 0
    push 25
    jmp isr_common
isr26:
    cli
    push 0
    push 26
    jmp isr_common
isr27:
    cli
    push 0
    push 27
    jmp isr_common
isr28:
    cli
    push 0
    push 28
    jmp isr_common
isr29:
    cli
    push 0
    push 29
    jmp isr_common
isr30:
    cli
    push 0
    push 30
    jmp isr_common
isr31:
    cli
    push 0
    push 31
    jmp isr_common
isr32:
    cli
    push 0
    push 32
    jmp isr_common
isr33:
    cli
    push 0
    push 33
    jmp isr_common
isr34:
    cli
    push 0
    push 34
    jmp isr_common
isr35:
    cli
    push 0
    push 35
    jmp isr_common
isr36:
    cli
    push 0
    push 36
    jmp isr_common
isr37:
    cli
    push 0
    push 37
    jmp isr_common
isr38:
    cli
    push 0
    push 38
    jmp isr_common
isr39:
    cli
    push 0
    push 39
    jmp isr_common
isr40:
    cli
    push 0
    push 40
    jmp isr_common
isr41:
    cli
    push 0
    push 41
    jmp isr_common
isr42:
    cli
    push 0
    push 42
    jmp isr_common
isr43:
    cli
    push 0
    push 43
    jmp isr_common
isr44:
    cli
    push 0
    push 44
    jmp isr_common
isr45:
    cli
    push 0
    push 45
    jmp isr_common
isr46:
    cli
    push 0
    push 46
    jmp isr_common
isr47:
    cli
    push 0
    push 47
    jmp isr_common
isr48:
    cli
    push 0
    push 48
    jmp isr_common
isr49:
    cli
    push 0
    push 49
    jmp isr_common
isr50:
    cli
    push 0
    push 50
    jmp isr_common
isr51:
    cli
    push 0
    push 51
    jmp isr_common
isr52:
    cli
    push 0
    push 52
    jmp isr_common
isr53:
    cli
    push 0
    push 53
    jmp isr_common
isr54:
    cli
    push 0
    push 54
    jmp isr_common
isr55:
    cli
    push 0
    push 55
    jmp isr_common
isr56:
    cli
    push 0
    push 56
    jmp isr_common
isr57:
    cli
    push 0
    push 57
    jmp isr_common
isr58:
    cli
    push 0
    push 58
    jmp isr_common
isr59:
    cli
    push 0
    push 59
    jmp isr_common
isr60:
    cli
    push 0
    push 60
    jmp isr_common
isr61:
    cli
    push 0
    push 61
    jmp isr_common
isr62:
    cli
    push 0
    push 62
    jmp isr_common
isr63:
    cli
    push 0
    push 63
    jmp isr_common
isr64:
    cli
    push 0
    push 64
    jmp isr_common
isr65:
    cli
    push 0
    push 65
    jmp isr_common
isr66:
    cli
    push 0
    push 66
    jmp isr_common
isr67:
    cli
    push 0
    push 67
    jmp isr_common
isr68:
    cli
    push 0
    push 68
    jmp isr_common
isr69:
    cli
    push 0
    push 69
    jmp isr_common
isr70:
    cli
    push 0
    push 70
    jmp isr_common
isr71:
    cli
    push 0
    push 71
    jmp isr_common
isr72:
    cli
    push 0
    push 72
    jmp isr_common
isr73:
    cli
    push 0
    push 73
    jmp isr_common
isr74:
    cli
    push 0
    push 74
    jmp isr_common
isr75:
    cli
    push 0
    push 75
    jmp isr_common
isr76:
    cli
    push 0
    push 76
    jmp isr_common
isr77:
    cli
    push 0
    push 77
    jmp isr_common
isr78:
    cli
    push 0
    push 78
    jmp isr_common
isr79:
    cli
    push 0
    push 79
    jmp isr_common
isr80:
    cli
    push 0
    push 80
    jmp isr_common
isr81:
    cli
    push 0
    push 81
    jmp isr_common
isr82:
    cli
    push 0
    push 82
    jmp isr_common
isr83:
    cli
    push 0
    push 83
    jmp isr_common
isr84:
    cli
    push 0
    push 84
    jmp isr_common
isr85:
    cli
    push 0
    push 85
    jmp isr_common
isr86:
    cli
    push 0
    push 86
    jmp isr_common
isr87:
    cli
    push 0
    push 87
    jmp isr_common
isr88:
    cli
    push 0
    push 88
    jmp isr_common
isr89:
    cli
    push 0
    push 89
    jmp isr_common
isr90:
    cli
    push 0
    push 90
    jmp isr_common
isr91:
    cli
    push 0
    push 91
    jmp isr_common
isr92:
    cli
    push 0
    push 92
    jmp isr_common
isr93:
    cli
    push 0
    push 93
    jmp isr_common
isr94:
    cli
    push 0
    push 94
    jmp isr_common
isr95:
    cli
    push 0
    push 95
    jmp isr_common
isr96:
    cli
    push 0
    push 96
    jmp isr_common
isr97:
    cli
    push 0
    push 97
    jmp isr_common
isr98:
    cli
    push 0
    push 98
    jmp isr_common
isr99:
    cli
    push 0
    push 99
    jmp isr_common
isr100:
    cli
    push 0
    push 100
    jmp isr_common
isr101:
    cli
    push 0
    push 101
    jmp isr_common
isr102:
    cli
    push 0
    push 102
    jmp isr_common
isr103:
    cli
    push 0
    push 103
    jmp isr_common
isr104:
    cli
    push 0
    push 104
    jmp isr_common
isr105:
    cli
    push 0
    push 105
    jmp isr_common
isr106:
    cli
    push 0
    push 106
    jmp isr_common
isr107:
    cli
    push 0
    push 107
    jmp isr_common
isr108:
    cli
    push 0
    push 108
    jmp isr_common
isr109:
    cli
    push 0
    push 109
    jmp isr_common
isr110:
    cli
    push 0
    push 110
    jmp isr_common
isr111:
    cli
    push 0
    push 111
    jmp isr_common
isr112:
    cli
    push 0
    push 112
    jmp isr_common
isr113:
    cli
    push 0
    push 113
    jmp isr_common
isr114:
    cli
    push 0
    push 114
    jmp isr_common
isr115:
    cli
    push 0
    push 115
    jmp isr_common
isr116:
    cli
    push 0
    push 116
    jmp isr_common
isr117:
    cli
    push 0
    push 117
    jmp isr_common
isr118:
    cli
    push 0
    push 118
    jmp isr_common
isr119:
    cli
    push 0
    push 119
    jmp isr_common
isr120:
    cli
    push 0
    push 120
    jmp isr_common
isr121:
    cli
    push 0
    push 121
    jmp isr_common
isr122:
    cli
    push 0
    push 122
    jmp isr_common
isr123:
    cli
    push 0
    push 123
    jmp isr_common
isr124:
    cli
    push 0
    push 124
    jmp isr_common
isr125:
    cli
    push 0
    push 125
    jmp isr_common
isr126:
    cli
    push 0
    push 126
    jmp isr_common
isr127:
    cli
    push 0
    push 127
    jmp isr_common
isr128:
    cli
    push 0
    push 128
    jmp isr_common
isr129:
    cli
    push 0
    push 129
    jmp isr_common
isr130:
    cli
    push 0
    push 130
    jmp isr_common
isr131:
    cli
    push 0
    push 131
    jmp isr_common
isr132:
    cli
    push 0
    push 132
    jmp isr_common
isr133:
    cli
    push 0
    push 133
    jmp isr_common
isr134:
    cli
    push 0
    push 134
    jmp isr_common
isr135:
    cli
    push 0
    push 135
    jmp isr_common
isr136:
    cli
    push 0
    push 136
    jmp isr_common
isr137:
    cli
    push 0
    push 137
    jmp isr_common
isr138:
    cli
    push 0
    push 138
    jmp isr_common
isr139:
    cli
    push 0
    push 139
    jmp isr_common
isr140:
    cli
    push 0
    push 140
    jmp isr_common
isr141:
    cli
    push 0
    push 141
    jmp isr_common
isr142:
    cli
    push 0
    push 142
    jmp isr_common
isr143:
    cli
    push 0
    push 143
    jmp isr_common
isr144:
    cli
    push 0
    push 144
    jmp isr_common
isr145:
    cli
    push 0
    push 145
    jmp isr_common
isr146:
    cli
    push 0
    push 146
    jmp isr_common
isr147:
    cli
    push 0
    push 147
    jmp isr_common
isr148:
    cli
    push 0
    push 148
    jmp isr_common
isr149:
    cli
    push 0
    push 149
    jmp isr_common
isr150:
    cli
    push 0
    push 150
    jmp isr_common
isr151:
    cli
    push 0
    push 151
    jmp isr_common
isr152:
    cli
    push 0
    push 152
    jmp isr_common
isr153:
    cli
    push 0
    push 153
    jmp isr_common
isr154:
    cli
    push 0
    push 154
    jmp isr_common
isr155:
    cli
    push 0
    push 155
    jmp isr_common
isr156:
    cli
    push 0
    push 156
    jmp isr_common
isr157:
    cli
    push 0
    push 157
    jmp isr_common
isr158:
    cli
    push 0
    push 158
    jmp isr_common
isr159:
    cli
    push 0
    push 159
    jmp isr_common
isr160:
    cli
    push 0
    push 160
    jmp isr_common
isr161:
    cli
    push 0
    push 161
    jmp isr_common
isr162:
    cli
    push 0
    push 162
    jmp isr_common
isr163:
    cli
    push 0
    push 163
    jmp isr_common
isr164:
    cli
    push 0
    push 164
    jmp isr_common
isr165:
    cli
    push 0
    push 165
    jmp isr_common
isr166:
    cli
    push 0
    push 166
    jmp isr_common
isr167:
    cli
    push 0
    push 167
    jmp isr_common
isr168:
    cli
    push 0
    push 168
    jmp isr_common
isr169:
    cli
    push 0
    push 169
    jmp isr_common
isr170:
    cli
    push 0
    push 170
    jmp isr_common
isr171:
    cli
    push 0
    push 171
    jmp isr_common
isr172:
    cli
    push 0
    push 172
    jmp isr_common
isr173:
    cli
    push 0
    push 173
    jmp isr_common
isr174:
    cli
    push 0
    push 174
    jmp isr_common
isr175:
    cli
    push 0
    push 175
    jmp isr_common
isr176:
    cli
    push 0
    push 176
    jmp isr_common
isr177:
    cli
    push 0
    push 177
    jmp isr_common
isr178:
    cli
    push 0
    push 178
    jmp isr_common
isr179:
    cli
    push 0
    push 179
    jmp isr_common
isr180:
    cli
    push 0
    push 180
    jmp isr_common
isr181:
    cli
    push 0
    push 181
    jmp isr_common
isr182:
    cli
    push 0
    push 182
    jmp isr_common
isr183:
    cli
    push 0
    push 183
    jmp isr_common
isr184:
    cli
    push 0
    push 184
    jmp isr_common
isr185:
    cli
    push 0
    push 185
    jmp isr_common
isr186:
    cli
    push 0
    push 186
    jmp isr_common
isr187:
    cli
    push 0
    push 187
    jmp isr_common
isr188:
    cli
    push 0
    push 188
    jmp isr_common
isr189:
    cli
    push 0
    push 189
    jmp isr_common
isr190:
    cli
    push 0
    push 190
    jmp isr_common
isr191:
    cli
    push 0
    push 191
    jmp isr_common
isr192:
    cli
    push 0
    push 192
    jmp isr_common
isr193:
    cli
    push 0
    push 193
    jmp isr_common
isr194:
    cli
    push 0
    push 194
    jmp isr_common
isr195:
    cli
    push 0
    push 195
    jmp isr_common
isr196:
    cli
    push 0
    push 196
    jmp isr_common
isr197:
    cli
    push 0
    push 197
    jmp isr_common
isr198:
    cli
    push 0
    push 198
    jmp isr_common
isr199:
    cli
    push 0
    push 199
    jmp isr_common
isr200:
    cli
    push 0
    push 200
    jmp isr_common
isr201:
    cli
    push 0
    push 201
    jmp isr_common
isr202:
    cli
    push 0
    push 202
    jmp isr_common
isr203:
    cli
    push 0
    push 203
    jmp isr_common
isr204:
    cli
    push 0
    push 204
    jmp isr_common
isr205:
    cli
    push 0
    push 205
    jmp isr_common
isr206:
    cli
    push 0
    push 206
    jmp isr_common
isr207:
    cli
    push 0
    push 207
    jmp isr_common
isr208:
    cli
    push 0
    push 208
    jmp isr_common
isr209:
    cli
    push 0
    push 209
    jmp isr_common
isr210:
    cli
    push 0
    push 210
    jmp isr_common
isr211:
    cli
    push 0
    push 211
    jmp isr_common
isr212:
    cli
    push 0
    push 212
    jmp isr_common
isr213:
    cli
    push 0
    push 213
    jmp isr_common
isr214:
    cli
    push 0
    push 214
    jmp isr_common
isr215:
    cli
    push 0
    push 215
    jmp isr_common
isr216:
    cli
    push 0
    push 216
    jmp isr_common
isr217:
    cli
    push 0
    push 217
    jmp isr_common
isr218:
    cli
    push 0
    push 218
    jmp isr_common
isr219:
    cli
    push 0
    push 219
    jmp isr_common
isr220:
    cli
    push 0
    push 220
    jmp isr_common
isr221:
    cli
    push 0
    push 221
    jmp isr_common
isr222:
    cli
    push 0
    push 222
    jmp isr_common
isr223:
    cli
    push 0
    push 223
    jmp isr_common
isr224:
    cli
    push 0
    push 224
    jmp isr_common
isr225:
    cli
    push 0
    push 225
    jmp isr_common
isr226:
    cli
    push 0
    push 226
    jmp isr_common
isr227:
    cli
    push 0
    push 227
    jmp isr_common
isr228:
    cli
    push 0
    push 228
    jmp isr_common
isr229:
    cli
    push 0
    push 229
    jmp isr_common
isr230:
    cli
    push 0
    push 230
    jmp isr_common
isr231:
    cli
    push 0
    push 231
    jmp isr_common
isr232:
    cli
    push 0
    push 232
    jmp isr_common
isr233:
    cli
    push 0
    push 233
    jmp isr_common
isr234:
    cli
    push 0
    push 234
    jmp isr_common
isr235:
    cli
    push 0
    push 235
    jmp isr_common
isr236:
    cli
    push 0
    push 236
    jmp isr_common
isr237:
    cli
    push 0
    push 237
    jmp isr_common
isr238:
    cli
    push 0
    push 238
    jmp isr_common
isr239:
    cli
    push 0
    push 239
    jmp isr_common
isr240:
    cli
    push 0
    push 240
    jmp isr_common
isr241:
    cli
    push 0
    push 241
    jmp isr_common
isr242:
    cli
    push 0
    push 242
    jmp isr_common
isr243:
    cli
    push 0
    push 243
    jmp isr_common
isr244:
    cli
    push 0
    push 244
    jmp isr_common
isr245:
    cli
    push 0
    push 245
    jmp isr_common
isr246:
    cli
    push 0
    push 246
    jmp isr_common
isr247:
    cli
    push 0
    push 247
    jmp isr_common
isr248:
    cli
    push 0
    push 248
    jmp isr_common
isr249:
    cli
    push 0
    push 249
    jmp isr_common
isr250:
    cli
    push 0
    push 250
    jmp isr_common
isr251:
    cli
    push 0
    push 251
    jmp isr_common
isr252:
    cli
    push 0
    push 252
    jmp isr_common
isr253:
    cli
    push 0
    push 253
    jmp isr_common
isr254:
    cli
    push 0
    push 254
    jmp isr_common
isr255:
    cli
    push 0
    push 255
    jmp isr_common


// Vector table

.section .data
.global ISR_TABLE
ISR_TABLE:
  .quad isr0
  .quad isr1
  .quad isr2
  .quad isr3
  .quad isr4
  .quad isr5
  .quad isr6
  .quad isr7
  .quad isr8
  .quad isr9
  .quad isr10
  .quad isr11
  .quad isr12
  .quad isr13
  .quad isr14
  .quad isr15
  .quad isr16
  .quad isr17
  .quad isr18
  .quad isr19
  .quad isr20
  .quad isr21
  .quad isr22
  .quad isr23
  .quad isr24
  .quad isr25
  .quad isr26
  .quad isr27
  .quad isr28
  .quad isr29
  .quad isr30
  .quad isr31
  .quad isr32
  .quad isr33
  .quad isr34
  .quad isr35
  .quad isr36
  .quad isr37
  .quad isr38
  .quad isr39
  .quad isr40
  .quad isr41
  .quad isr42
  .quad isr43
  .quad isr44
  .quad isr45
  .quad isr46
  .quad isr47
  .quad isr48
  .quad isr49
  .quad isr50
  .quad isr51
  .quad isr52
  .quad isr53
  .quad isr54
  .quad isr55
  .quad isr56
  .quad isr57
  .quad isr58
  .quad isr59
  .quad isr60
  .quad isr61
  .quad isr62
  .quad isr63
  .quad isr64
  .quad isr65
  .quad isr66
  .quad isr67
  .quad isr68
  .quad isr69
  .quad isr70
  .quad isr71
  .quad isr72
  .quad isr73
  .quad isr74
  .quad isr75
  .quad isr76
  .quad isr77
  .quad isr78
  .quad isr79
  .quad isr80
  .quad isr81
  .quad isr82
  .quad isr83
  .quad isr84
  .quad isr85
  .quad isr86
  .quad isr87
  .quad isr88
  .quad isr89
  .quad isr90
  .quad isr91
  .quad isr92
  .quad isr93
  .quad isr94
  .quad isr95
  .quad isr96
  .quad isr97
  .quad isr98
  .quad isr99
  .quad isr100
  .quad isr101
  .quad isr102
  .quad isr103
  .quad isr104
  .quad isr105
  .quad isr106
  .quad isr107
  .quad isr108
  .quad isr109
  .quad isr110
  .quad isr111
  .quad isr112
  .quad isr113
  .quad isr114
  .quad isr115
  .quad isr116
  .quad isr117
  .quad isr118
  .quad isr119
  .quad isr120
  .quad isr121
  .quad isr122
  .quad isr123
  .quad isr124
  .quad isr125
  .quad isr126
  .quad isr127
  .quad isr128
  .quad isr129
  .quad isr130
  .quad isr131
  .quad isr132
  .quad isr133
  .quad isr134
  .quad isr135
  .quad isr136
  .quad isr137
  .quad isr138
  .quad isr139
  .quad isr140
  .quad isr141
  .quad isr142
  .quad isr143
  .quad isr144
  .quad isr145
  .quad isr146
  .quad isr147
  .quad isr148
  .quad isr149
  .quad isr150
  .quad isr151
  .quad isr152
  .quad isr153
  .quad isr154
  .quad isr155
  .quad isr156
  .quad isr157
  .quad isr158
  .quad isr159
  .quad isr160
  .quad isr161
  .quad isr162
  .quad isr163
  .quad isr164
  .quad isr165
  .quad isr166
  .quad isr167
  .quad isr168
  .quad isr169
  .quad isr170
  .quad isr171
  .quad isr172
  .quad isr173
  .quad isr174
  .quad isr175
  .quad isr176
  .quad isr177
  .quad isr178
  .quad isr179
  .quad isr180
  .quad isr181
  .quad isr182
  .quad isr183
  .quad isr184
  .quad isr185
  .quad isr186
  .quad isr187
  .quad isr188
  .quad isr189
  .quad isr190
  .quad isr191
  .quad isr192
  .quad isr193
  .quad isr194
  .quad isr195
  .quad isr196
  .quad isr197
  .quad isr198
  .quad isr199
  .quad isr200
  .quad isr201
  .quad isr202
  .quad isr203
  .quad isr204
  .quad isr205
  .quad isr206
  .quad isr207
  .quad isr208
  .quad isr209
  .quad isr210
  .quad isr211
  .quad isr212
  .quad isr213
  .quad isr214
  .quad isr215
  .quad isr216
  .quad isr217
  .quad isr218
  .quad isr219
  .quad isr220
  .quad isr221
  .quad isr222
  .quad isr223
  .quad isr224
  .quad isr225
  .quad isr226
  .quad isr227
  .quad isr228
  .quad isr229
  .quad isr230
  .quad isr231
  .quad isr232
  .quad isr233
  .quad isr234
  .quad isr235
  .quad isr236
  .quad isr237
  .quad isr238
  .quad isr239
  .quad isr240
  .quad isr241
  .quad isr242
  .quad isr243
  .quad isr244
  .quad isr245
  .quad isr246
  .quad isr247
  .quad isr248
  .quad isr249
  .quad isr250
  .quad isr251
  .quad isr252
  .quad isr253
  .quad isr254
  .quad isr255
